name: Main

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name:
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GSC tool
        uses: ./

      - name: Compile GSC
        run: gsc-tool -m comp -g iw5 -s pc ./test/test.gsc
